<a href="https://colab.research.google.com/github/nsaedae/Colab/blob/master/Ch03.%EB%94%A5%EB%9F%AC%EB%8B%9D%20%EC%8B%A4%EC%8A%B5/4_%EB%94%A5%EB%9F%AC%EB%8B%9D_CNN_%EB%AA%A8%EB%8D%B8_%ED%85%8C%EC%8A%A4%ED%8A%B8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [31]:
"""
날짜 : 2022/05/10
이름 : 김철학
내용 : 딥러닝 CNN 모델 테스트하기
"""
import matplotlib.pyplot as plt
import numpy as np
import tensorflow as tf
from tensorflow.keras.datasets.cifar10 import load_data
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.models import load_model
from keras.preprocessing.image import load_img, img_to_array
from PIL import Image
tf.__version__

'2.8.0'

In [2]:
#데이터 불러오기
(cifar_train_data, cifar_train_label), (cifar_test_data, cifar_test_label) = load_data()

170508288/170498071 [==============================] - 4s 0us/step


In [3]:
#모델학습을 위한 데이터 전처리(정규화)
cifar_train_data2 = cifar_train_data / 255
cifar_test_data2 = cifar_test_data / 255

In [4]:
#데이터 라벨을 범주형(one-hot encoding)으로 변환
cifar_train_label2 = to_categorical(cifar_train_label)
cifar_test_label2 = to_categorical(cifar_test_label)
cifar_train_label2[1]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 1.], dtype=float32)

In [ ]:
#외부 학습모델 불러오기
model = load_model('/content/drive/MyDrive/파이썬 데이터 과학 실습/file/cifar_model.h5')
model.summary()

In [8]:
#모델 테스트
result = model.evaluate(cifar_test_data2, cifar_test_label2)
result

313/313 [==============================] - 14s 42ms/step - loss: 1.4942 - acc: 0.7577


[1.4941719770431519, 0.7577000260353088]

In [32]:
###############################################################
#이미지 로드 함수 정의
def load_image(filename):
	# load the image
	img = load_img(filename, target_size=(32, 32))
	# convert to array
	img = img_to_array(img)
	# reshape into a single sample with 3 channels
	img = img.reshape(1, 32, 32, 3)
	# prepare pixel data
	img = img.astype('float32')
	img = img / 255.0
	return img

In [33]:
img = load_image('/content/drive/MyDrive/파이썬 데이터 과학 실습/file/flog.jpg')
img

array([[[[1.        , 1.        , 0.9843137 ],
         [1.        , 1.        , 0.98039216],
         [1.        , 1.        , 0.9647059 ],
         ...,
         [0.99607843, 1.        , 0.98039216],
         [0.9882353 , 0.9882353 , 0.99607843],
         [0.99607843, 0.99607843, 1.        ]],

        [[1.        , 0.99607843, 1.        ],
         [1.        , 0.99607843, 1.        ],
         [1.        , 1.        , 0.9843137 ],
         ...,
         [0.99607843, 0.99215686, 0.972549  ],
         [0.99607843, 0.99607843, 1.        ],
         [0.9882353 , 1.        , 1.        ]],

        [[1.        , 0.99215686, 1.        ],
         [1.        , 0.99215686, 1.        ],
         [1.        , 0.99607843, 1.        ],
         ...,
         [1.        , 0.99607843, 0.9843137 ],
         [1.        , 0.99607843, 1.        ],
         [0.96862745, 0.9882353 , 1.        ]],

        ...,

        [[1.        , 0.99215686, 1.        ],
         [0.99215686, 0.98039216, 1.        ]

In [36]:
#이미지 모델 테스트
result = model.predict(img)
result.round()

array([[0., 0., 0., 0., 0., 0., 1., 0., 0., 0.]], dtype=float32)