<a href="https://colab.research.google.com/github/nsaedae/Colab/blob/master/Ch01.%ED%8C%8C%EC%9D%B4%EC%8D%AC%20%EB%8D%B0%EC%9D%B4%ED%84%B0%20%EB%B6%84%EC%84%9D%20%EA%B8%B0%EC%B4%88/2_Numpy_%EC%8B%A4%EC%8A%B5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
"""
날짜 : 2022/04/25
이름 : 김철학
내용 : 파이썬 Numpy 패키지 실습

Numpy 라이브러리
 - 고성능 수치계산을 위한 파이썬 라이브러리
 - 파이썬 기본 리스트 보다 더 크고 빠른 연산을 위한 리스트를 제공
 - 행렬이나 대규모 다차원 배열 처리를 지원
"""
import numpy as np

In [ ]:
# 벡터(Numpy 자료구조)
v1 = np.array([1, 2, 3, 4, 5])
print(v1)

v2 = np.arange(10)
print(v2)

v3 = np.arange(100)
print(v3)

[1 2 3 4 5]
[0 1 2 3 4 5 6 7 8 9]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [ ]:
#0 ~ 1 사이 임의의 실수 100개
rand1 = np.random.rand(100)
rand1

In [ ]:
#표준 정규분포를 따르는 실수 100개
rand2 = np.random.randn(100)
rand2

In [ ]:
#행렬(Numpy 자료구조)
m1 = np.array([[1, 2], [3, 4]])
print(m1)

m2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(m2)

m3 = np.zeros([2, 3])
print(m3)

In [ ]:
#단위행렬
e1 = np.identity(2)
print(e1)

e2 = np.identity(3)
print(e2)

In [16]:
#역행렬
im1 = np.linalg.inv(m1)
print(im1)

result = m1.dot(im1)
print(result.round())

[[-2.   1. ]
 [ 1.5 -0.5]]
[[1. 0.]
 [0. 1.]]


In [20]:
#행렬 인덱싱
mat = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(mat)

print('r1 :', mat[0, 0])
print('r2 :', mat[0, :])
print('r3 :', mat[:, 0])

print('r4 :', mat[0:2, 0:2])
print('r5 :', mat[:, 0:2])
print('r6 :', mat[:, 2:4])
print('r7 :', mat[1:3, 1:3])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
r1 : 1
r2 : [1 2 3 4]
r3 : [1 5 9]
r4 : [[1 2]
 [5 6]]
r5 : [[ 1  2]
 [ 5  6]
 [ 9 10]]
r6 : [[ 3  4]
 [ 7  8]
 [11 12]]
r7 : [[ 6  7]
 [10 11]]
